[build-system]
requires = ["setuptools >= 61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "rep_test_srv"
description = "A CommCare HQ Repeater Test Service"
version = "0.1.0"
dependencies = [
    "quart",
    "redis"
]
